### ISSUE TITLE
Organize main CSS file to modular

### ISSUE THREAD

**Issue by hibuno** [nuxtjs-id/nuxtjs.id#1]
Hi guys,

In my opinion, we can boost styling project with making CSS file modular or component base.
And we can start with organize this file **~/assets/style/style.css**.

Thank you

**Comment by PerjakaSunda** [comment]
Due to standardization and source efficiency, the modular css default used by Vuetify is the Stylus. For css style modification, please use "stylus" or use custom css on the existing file.
